__author__ = 'h_hack'

SOCIAL_AUTH_TWITTER_KEY = '2AZrgcjGa6UaFVZaF4oXnqZHi'
SOCIAL_AUTH_TWITTER_SECRET = 'qmPtUoccyUpycM9mdt8o1RWslFbP33UvPk08YHCUQ8CZevXzqa'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
